"use client";
import { useRef,useState } from "react";
import { Button } from "@/components/ui/button";
import { Film,Headphones,Pause,Play,RotateCcw } from "lucide-react";
const film="https://archive.org/download/MetropolisGriggsMoviedrome/title00.mp4";
const album="https://www.youtube.com/embed/videoseries?list=OLAK5uy_lrCrcAdxFG4aMzMrebs7o9TU384xyF240";
export default function Home(){
 const video=useRef<HTMLVideoElement>(null);const pendingSync=useRef(false);const [run,setRun]=useState(0);const [started,setStarted]=useState(false);
 const sync=()=>{setRun(v=>v+1);setStarted(true);pendingSync.current=true;const v=video.current;if(v){v.pause();v.currentTime=0}};
 const albumReady=()=>{if(!pendingSync.current)return;pendingSync.current=false;const v=video.current;if(v){v.pause();v.currentTime=0;setTimeout(()=>{v.currentTime=0;v.play().catch(()=>{})},120)}};
 const stop=()=>{pendingSync.current=false;video.current?.pause();setStarted(false)};
 const albumSrc=started?`${album}&autoplay=1&loop=1&playsinline=1&enablejsapi=1&run=${run}`:`${album}&loop=1&playsinline=1&enablejsapi=1`;
 return <main><header><a className="logo" href="#top"><span>ASTRA</span>FLIX</a><span className="edition">METROPOLIS · DARK SIDE EDITION</span><span className="status">SYNC-LOCK FILM DECK</span></header>
 <section id="top" className="intro"><div><span className="eyebrow">A FILM / SOUND EXPERIMENT</span><h1>THE CITY<br/>HAS A <em>PULSE.</em></h1><p>Astraflix pairs an Archive-hosted, public-domain-marked print of Fritz Lang’s <i>Metropolis</i> with Pink Floyd’s official YouTube Music album playlist. The film now uses Astraflix’s own controls instead of a second Archive play screen.</p></div><div className="orb"><span>1927 × 1973</span><b>∞</b><small>LOOPED<br/>SCORE</small></div></section>
 <section className="theater"><div className="screen"><video ref={video} src={film} controls muted playsInline preload="metadata" style={{width:"100%",height:"568px",background:"#000",objectFit:"contain"}}/><div className="screenTag"><Film size={14}/> FILE SERVED BY INTERNET ARCHIVE · PUBLIC DOMAIN MARK 1.0</div></div><aside className="console"><span className="eyebrow">ASTRAFLIX SYNC DECK</span><h2>Dark Side of the Moon</h2><p>The album remains in YouTube’s attributed player. Astraflix does not upload or redistribute it.</p><div style={{margin:"28px 0 16px",border:"1px solid #3b414d",background:"#050608",padding:"8px"}}><iframe key={`album-${run}-${started}`} title="Pink Floyd — The Dark Side of the Moon" src={albumSrc} onLoad={albumReady} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen style={{display:"block",width:"100%",height:"220px",border:0}}/></div><div className="timeLabels"><span>OFFICIAL ALBUM SOURCE</span><span>PLAYLIST LOOP: ON</span></div><div className="transport"><Button onClick={sync}>{started?<RotateCcw/>:<Play/>}{started?"Re-sync both":"Start film + score"}</Button><Button variant="outline" disabled={!started} onClick={stop}><Pause/>Stop</Button></div><div className="cue"><span>SYNC RECOVERY</span><p>The film is held at its opening frame while the album player initializes. When the album cue is ready, Astraflix releases the film into the same start moment. If a YouTube ad or buffering knocks the pairing apart, tap Re-sync both after the interruption.</p></div></aside></section>
 <section className="notes"><article><Headphones/><span>01</span><h3>No uploads</h3><p>Astraflix assembles supported source players; visitors do not provide downloaded files.</p></article><article><RotateCcw/><span>02</span><h3>Re-sync anytime</h3><p>The shared recovery button holds the movie at zero while the official album player reloads, then releases the movie at the album’s opening cue.</p></article><article><Film/><span>03</span><h3>No Archive double tap</h3><p>The Archive-hosted movie now plays through a native Astraflix video control.</p></article></section>
 <footer><div className="logo"><span>ASTRA</span>FLIX</div><p>Curated alternate-soundtrack cinema · Source players remain attributed</p><span>Infinity ® · 2026</span></footer></main>}
